name: pr_checks

on:
  pull_request:
    branches:
      - master

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout previous commit
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.base.ref}}

      - name: Get previous app version
        run: echo "prev_app_version=$(jq -rM '.version' package.json)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get app version
        run: echo "app_version=$(jq -rM '.version' package.json)" >> $GITHUB_ENV

      - name: App version must increase
        run: |
          [ "${{env.prev_app_version}}" != "${{env.app_version}}" ] && true || false

      - name: Build test image
        run: docker build -t hydra-test . # --target test .

      - name: Run tests
        run: echo docker run --rm hydra-test
